name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0+3
  dio: ^5.6.0
  logger: ^2.4.0
  json_annotation: ^4.9.0
  toggle_switch: ^2.3.0
  connectivity_plus: ^6.0.5
  mask_text_input_formatter: ^2.9.0
  carousel_slider: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  formz: ^0.7.0
  hive_generator: ^2.0.1

  
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/    
   
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets\fonts\Montserrat-SemiBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
